name: Quattor
description: Quattor news and documentation
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude: [vendor, .idea]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
collections:
  aquilon:
    output: true
    permalink: /aquilon/:title.html
  development:
    output: true
    permalink: /development/:title.html
  other:
    output: true
    permalink: /other/:title.html
  quattor:
    output: true
    permalink: /quattor/:title.html
  template_library:
    output: true
    permalink: /template_library/:title.html
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
